"""Add system_prompt to Tenant model

Revision ID: 66c9e4aafc9e
Revises: 8adfa00db3b0
Create Date: 2025-04-14 11:09:04.546748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c9e4aafc9e'
down_revision: Union[str, None] = '8adfa00db3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'system_prompt')
    # ### end Alembic commands ###
